[package]
name = "todo_task"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"]}
chrono = { version = "0.4", features = ["serde"] }
